spring:
  application:
    name: app
  datasource:
    url: jdbc:postgresql://aws-0-ap-southeast-1.pooler.supabase.com:6543/postgres
    username: postgres.shdxsftyxxndtpqmmtcs
    password: vBLR4VsOvDnILiOE
    driver-class-name: org.postgresql.Driver
    schema: mining

    hikari:
      connection-timeout: 30000
      maximum-pool-size: 10

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        default_schema: mining

app:
  prifix: api
  jwt:
    secret: "change-this-super-long-secret-string-please-yeee-ichangeit"
    expiration: 3600000 # 1 jam (ms)
supabase:
  url: ${SUPABASE_URL}
  key: ${SUPABASE_ANON_KEY}
  bucket-name : ${BUCKET_SUPABASE_NAME}



