spring:
  application:
    name: app
  datasource:
    url: ${DATABASE_URL}
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}
    driver-class-name: org.postgresql.Driver
    schema: ${DATABASE_SCHEMA}

    hikari:
      connection-timeout: 30000
      maximum-pool-size: 10

  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        default_schema: ${DATABASE_SCHEMA}

  jackson:
    time-zone: Asia/Jakarta

app:
  prifix: api
  api-base-url: ${URL_DOMAIN}
  jwt:
    secret: "change-this-super-long-secret-string-please-yeee-ichangeit"
    expiration: 3600000 # 1 jam (ms)
supabase:
  url: ${SUPABASE_URL}
  key: ${SUPABASE_ANON_KEY}
  bucket-name : ${BUCKET_SUPABASE_NAME}



